travis:
  secure:
    BINSTAR_TOKEN: whqqrudfNuoZsRmHDQG4h1cOOxEoKh8EzSXHpz8tCHCDYGhjzGsBYur50W29UlsRMCcLT+cjK1pFrc96aLY2jpD8E0jOsYi2xV8kGyFkwTrzIPEoGoTvX1ECtU2TKg8G1oa2bxjAvFJBI7/25sP18pkZ+bQ9XpVLV6cuIx0uRxzI2u0DVuridMPPtFDKUIvGdii6i5oYJWmpBwsLi3ImgadOU7KzE/INVX9r/xudGCs5fHc/8xoxuSgcmgZN7z0kNNWkLyNqPPPTwWD57LNbcJCi6DjfRKdG/yRtIieSG7s+gkRnTj+fyh7C3TPG6qbqrBeiI+71U/SM3jrw33MLW2/G/nwp4tSDMhygHG1nIMTpWkiPaPboMLrIMkbAkGgKhmUhfaeLHnF1cs8BUl2M4A+f/GZrREjfuUmPRi7FzgPJVLZpkvDRw9PswGpttWje1iSPRrwGbbnEF4IBPTty5iKnRoy+vZWVO3qUjB/vpIB9Ow/Y+XmfI105w4OsxI7M5jSJhV5pU/EbVnB5xzl8+ks7KxGz3wW3WB17lP9cdruzB7S/RBOYn/7X2fEtbjS+lqmlmRkuNl9wSYm/8eRgwHV5yKbIFdq8RYjzOltFsHEFfHV+6f7CW7+A0N9KvqQYT6f2rRZM0yYjQReI8M4BkktgQntXpcttvNuAhSwu7MI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
