travis:
  secure:
    BINSTAR_TOKEN: IQU13T9R7DAO2CFaJvfuzSoUQO5KP+3qFEi5qBnzyK4JSlckrNNlv24XnR0EOo2Sk4d7g+j6MkZgyha8jDjYV9mlsE+9bZaBPse3bkSYZY2PhD4870mmwgiRGmloIGUn/Xj72NnoS9cxgHHF6f9HQvzR3uQHSK/Ncy9Bbdi0SA5mhT2HCpW7E38pqyw+mUvYjODRvAlhyPrqJZ7l7ICwZKmq255LJ4YaZySD9OO1GwP89jjAc7popYf9CDU2sxIyj/dhRJLRaqyGL3AEkWhzl6FMmHJP4vdLn/PxCDhSV5qUMdqeGMivROyLTpG7is30A66QnslUnSPS4vP3W6keY+cdEGXQrN7Lu2atn5azKRE2WGha4eP0/ro14L3jtDO4L8hnj4QgHHQVe2PluZTw+TUNk0hyoE5YKzdzMRQ7WyorPtIKPsO9ZqLqiZi3ieYsmQ+JlL3g/YlsQIKeCRBw5UQFDeF0OrVnGfbNlaK5A6dchukEcHQb6tsq4FlmGB1s6l/jeEJFzpiQrfQnH7QeIzx/U31bgKk4mjEOuixWFS5wLfNlhC8E/7LQj8edtXMTTQCCheA2C29OdMsaDovgN/SEBQMQqn2gHCZqG1Wx4moBrWPf8LAQK6P+jBbbKnSALbEoiU7ERpOnnTwvHp8zPMc5TfNgAvZd7THO/zYsE48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
