appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: q1synVAI14MMOD63xg2hC7Ul3qFqqR/AokggiVQtvAPui4ZQT+Ha3iIOvbEhki76K136iL8J407Ivilmk73ATx6ksTTnSejhyLs6ANOYoHY6fMSr8lyUOBuXWNTHOtBI1gzQNNLG6rEGFEAE5LSG7Ahm9gCXQ+h0edjtmeCFb1GtQq3cqKk2XMm2j/ywgl1msnuziD8/NI87dalXdqQF3sxmt6TqdcDYjTOlknWKEmbRw8y4LZ43l+lehhWdEk2KxqZ8JoNjfrr/2wA8Hr4GTmnH7l5Vb3Czya8fWOYP4FWz7afF3LGEhZp4NvF6nb/rhRy9f/RP1zETwaSU400uhL4swPgMOTF9qmNTB9Lm4JOvNdfG3JQG0WrR2RTQb5L9zMtrchQWXwjAGGyqvFIlC8VfNPqc6zjZb/Q5WSinepnmgKsXZiC/jz5lXYhkxk3X2kkntH/9mE+SrzDbNS59KkCfs2m4WtWSP1WAaRO8wH4ddrq32mLVC2I8mcv1S9yrBRu1avGxw1NiAmcL6upJullPsL0/p4P7pocg6QlsBu0LDUJDJ5vFp/MOO5G88R8iZWYyIEyU8UGs9qusnUPYTH0ZlqEQIFYhdw4OdLh8mAWSyp0Sy8SvHler1Sq3QBRCsRX4lUgaVJH94W39ZYDZl05cbBlfut8s3NnXXrWQtjc=}
conda_forge_output_validation: true
